# Churn Prediction
Tujuan: Memprediksi pelanggan yang berhenti berlangganan (churn).

## 1. Data Loading
Tujuan: Menampilkan dan melihat gambaran besar data.

In [1]:
import pandas as pd

df = pd.read_csv("../data/processed/telco_clean.csv")
df.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,...,MonthlyCharges,TotalCharges,Churn,MultipleLines_No phone service,MultipleLines_Yes,InternetService_Fiber optic,InternetService_No,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,0,0,1,0,1,0,0,1,0,0,...,29.85,29.85,0,1,0,0,0,0,1,0
1,1,0,0,0,34,1,1,0,1,0,...,56.95,1889.50,0,0,0,0,0,0,0,1
2,1,0,0,0,2,1,1,1,0,0,...,53.85,108.15,1,0,0,0,0,0,0,1
3,1,0,0,0,45,0,1,0,1,1,...,42.30,1840.75,0,1,0,0,0,0,0,0
4,0,0,0,0,2,1,0,0,0,0,...,70.70,151.65,1,0,0,1,0,0,1,0

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7032 entries, 0 to 7031
Data columns (total 24 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   gender                                 7032 non-null   int64
 1   SeniorCitizen                          7032 non-null   int64
 2   Partner                                7032 non-null   int64
 3   Dependents                             7032 non-null   int64
 4   tenure                                 7032 non-null   int64
 5   PhoneService                           7032 non-null   int64
 6   OnlineSecurity                         7032 non-null   int64
 7   OnlineBackup                           7032 non-null   int64
 8   DeviceProtection                       7032 non-null   int64
 9   TechSupport                            7032 non-null   int64
 10  StreamingTV                            7032 non-null   int64
 11  StreamingMovies                        7032 non-null   int64
 12  Contract                               7032 non-null   int64
 13  PaperlessBilling                       7032 non-null   int64
 14  MonthlyCharges                         7032 non-null   float64
 15  TotalCharges                           7032 non-null   float64
 16  Churn                                  7032 non-null   int64
 17  MultipleLines_No phone service         7032 non-null   int64
 18  MultipleLines_Yes                      7032 non-null   int64
 19  InternetService_Fiber optic            7032 non-null   int64
 20  InternetService_No                     7032 non-null   int64
 21  PaymentMethod_Credit card (automatic)  7032 non-null   int64
 22  PaymentMethod_Electronic check         7032 non-null   int64
 23  PaymentMethod_Mailed check             7032 non-null   int64
dtypes: float64(2), int64(22)
memory usage: 1.3 MB

## 2. Data Splitting
Tujuan: Memisahkan dan membagi data.

In [4]:
# Pisahkan X dan y
X = df.drop("Churn", axis=1)
y = df["Churn"]

In [5]:
# Train Test Split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

## 3. Scaling
Tujuan: Mengubah nilai dari berbagai fitur (variabel) dalam dataset agar memiliki rentang skala yang seragam.

In [6]:
num_cols = [
    "tenure",
    "MonthlyCharges",
    "TotalCharges"
]

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train[num_cols] = scaler.fit_transform(X_train[num_cols])
X_test[num_cols] = scaler.fit_transform(X_test[num_cols])

In [7]:
X_train.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,...,PaperlessBilling,MonthlyCharges,TotalCharges,MultipleLines_No phone service,MultipleLines_Yes,InternetService_Fiber optic,InternetService_No,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
1408,1,0,1,1,1.321816,1,1,1,1,1,...,0,0.981556,1.659900,0,1,1,0,1,0,0
6992,1,0,0,0,-0.267410,0,0,0,1,1,...,0,-0.971546,-0.562252,1,0,0,0,0,1,0
3349,0,0,1,0,1.444064,1,0,1,1,1,...,0,0.837066,1.756104,0,1,1,0,1,0,0
4486,1,0,0,0,-1.204646,1,0,1,0,0,...,0,0.641092,-0.908326,0,0,1,0,0,1,0
3535,0,0,1,0,0.669826,0,1,0,0,0,...,0,-0.808787,-0.101561,1,0,0,0,0,0,0

In [8]:
X_test.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,...,PaperlessBilling,MonthlyCharges,TotalCharges,MultipleLines_No phone service,MultipleLines_Yes,InternetService_Fiber optic,InternetService_No,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
971,0,0,1,1,1.105564,1,0,1,0,1,...,1,0.398769,1.046427,0,0,0,0,1,0,0
618,0,0,0,0,-1.012686,1,0,1,0,0,...,1,0.485489,-0.756277,0,1,1,0,0,0,0
4282,0,0,0,0,0.901886,1,0,0,0,0,...,0,-1.464032,-0.506686,0,0,0,1,0,0,1
3715,0,0,0,0,-1.216364,1,0,0,0,0,...,0,-1.445688,-0.973464,0,0,0,1,0,0,1
4525,0,0,1,0,1.594391,1,0,1,1,0,...,1,1.372696,2.397603,0,1,1,0,0,0,0